### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ort163** [mailpile/www.mailpile.is#19]
Could you please clarify what is the licence of your website? Could you release in some kind of open license. It looks fantastic. Thanks

**Comment by BjarniRunar** [comment]
Hi @ort163! Thank you for your kind words and your interest.

Currently the website isn't released under any particular license, so normal copyright applies.

Most of the design is @bnvk 's hard work. If he is happy with us changing the license to something that lets people reuse and remix, we can consider doing so.

I don't see this as particularly important for the project though, and it could actually be detrimental. We don't want lookalike Mailpile websites cropping up all over the place and misleading people into downloading "fake" packages or donating to "fake" projects. Having copyright over the look and feel of our public page obviously won't prevent phishing (criminals don't care about copyright), but it is a tool we may want to use when responding to such abuses (their hosting providers might care!).

So I'm on the fence. Our focus is to release and share Mailpile itself, but I'm unsure whether open sourcing the website and branding is, on the whole, a net positive for the project.
